<?php

use Illuminate\Database\Seeder;
use App\Models\License;
use App\Services\RandomValueGenerator;

use Illuminate\Support\Facades\DB;

class LicensesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
      $seeds = $this->getSeeds();

      if ( !$this->confirmation($seeds) ) {
        print('処理を中止しました。' . PHP_EOL);
        exit();
      }

      DB::beginTransaction();

      try {
        foreach( $seeds as $license_id => $seed ) {
          $result = License::updateOrCreate(['license_id' => $license_id], $seed);

          if ( empty($result) ) throw new \Exception("Failed to save licenseCategory." . print_r($seed, true));
        }

        DB::commit();
      } catch( \Exception $e ) {
        DB::rollBack();
        logger()->error($e->getMessage());
        print("LicenseTableSeederの実行に失敗しました。{$e->getMessage()}" . PHP_EOL);
      }
    }

	private function getSeeds() {
		return collect([
			1 => ['name' => 'AT限定普通免許', 'display_name' => 'AT限定普通免許', 'license_category_id' => 1, 'sort_index' => 1],
			3 => ['name' => '準中型免許5t限定', 'display_name' => '準中型5t限定', 'license_category_id' => 1, 'sort_index' => 3],
			5 => ['name' => '中型免許8t限定', 'display_name' => '中型8t限定', 'license_category_id' => 1, 'sort_index' => 5],
			8 => ['name' => 'けん引一種免許', 'display_name' => 'けん引一種', 'license_category_id' => 1, 'sort_index' => 8],
			9 => ['name' => '普通第二種免許', 'display_name' => '普通二種', 'license_category_id' => 2, 'sort_index' => 1],
			10 => ['name' => '中型第二種免許', 'display_name' => '中型二種', 'license_category_id' => 2, 'sort_index' => 2],
			11 => ['name' => '大型第二種免許', 'display_name' => '大型二種', 'license_category_id' => 2, 'sort_index' => 3],
			12 => ['name' => '大型特殊第二種免許', 'display_name' => '大型特殊二種', 'license_category_id' => 2, 'sort_index' => 4],
			13 => ['name' => '大型けん引第二種免許', 'display_name' => '大型けん引二種', 'license_category_id' => 2, 'sort_index' => 5],
			14 => ['name' => '原動機付自転車免許', 'display_name' => '原付', 'license_category_id' => 3, 'sort_index' => 1],
			15 => ['name' => '小型二輪免許', 'display_name' => '小型二輪', 'license_category_id' => 3, 'sort_index' => 2],
			16 => ['name' => '普通二輪免許', 'display_name' => '普通二輪', 'license_category_id' => 3, 'sort_index' => 3],
			18 => ['name' => 'フォークリフト運転技能者', 'display_name' => 'フォークリフト免許', 'license_category_id' => 4, 'sort_index' => 1],
			19 => ['name' => '運行管理者（貨物）', 'display_name' => '運行管理者（貨物）', 'license_category_id' => 4, 'sort_index' => 2],
			20 => ['name' => '運行管理者（旅客）', 'display_name' => '運行管理者（旅客）', 'license_category_id' => 4, 'sort_index' => 3],
			21 => ['name' => '運行管理一般者講習受講', 'display_name' => '運行管理一般者講習受講', 'license_category_id' => 4, 'sort_index' => 4],
			22 => ['name' => 'クレーン・デリック運転士免許（床上運転式クレーン限定）', 'display_name' => '床上運転式クレーン', 'license_category_id' => 4, 'sort_index' => 5],
			23 => ['name' => '移動式クレーン運転士', 'display_name' => '移動式クレーン運転士', 'license_category_id' => 4, 'sort_index' => 6],
			24 => ['name' => '玉掛け技能講習', 'display_name' => '玉掛け', 'license_category_id' => 4, 'sort_index' => 7],
			25 => ['name' => '一級自動車整備士', 'display_name' => '一級自動車整備士', 'license_category_id' => 4, 'sort_index' => 8],
			26 => ['name' => '二級自動車整備士', 'display_name' => '二級自動車整備士', 'license_category_id' => 4, 'sort_index' => 9],
			27 => ['name' => '三級自動車整備士', 'display_name' => '三級自動車整備士', 'license_category_id' => 4, 'sort_index' => 10],
			28 => ['name' => '特殊整備士', 'display_name' => '特殊整備士', 'license_category_id' => 4, 'sort_index' => 11],
			29 => ['name' => '整備管理者', 'display_name' => '整備管理者', 'license_category_id' => 4, 'sort_index' => 12],
			30 => ['name' => '危険物取扱者乙種第4類', 'display_name' => '危険物取扱者乙種第4類', 'license_category_id' => 4, 'sort_index' => 13],
			31 => ['name' => '丙種危険物取扱者', 'display_name' => '丙種危険物取扱者', 'license_category_id' => 4, 'sort_index' => 14],
			32 => ['name' => '高圧ガス移動監視', 'display_name' => '高圧ガス移動監視', 'license_category_id' => 4, 'sort_index' => 15],
			6 => ['name' => '中型免許', 'display_name' => '中型免許', 'license_category_id' => 1, 'sort_index' => 6],
			2 => ['name' => '普通免許', 'display_name' => '普通免許', 'license_category_id' => 1, 'sort_index' => 2],
			7 => ['name' => '大型免許', 'display_name' => '大型免許', 'license_category_id' => 1, 'sort_index' => 7],
			4 => ['name' => '準中型免許', 'display_name' => '準中型免許', 'license_category_id' => 1, 'sort_index' => 4],
			17 => ['name' => '大型二輪免許', 'display_name' => '大型二輪', 'license_category_id' => 3, 'sort_index' => 4],
			33 => ['name' => '公認会計士', 'display_name' => '公認会計士', 'license_category_id' => 5, 'sort_index' => 1],
			34 => ['name' => '税理士', 'display_name' => '税理士', 'license_category_id' => 5, 'sort_index' => 2],
			35 => ['name' => '弁理士', 'display_name' => '弁理士', 'license_category_id' => 5, 'sort_index' => 3],
			36 => ['name' => '司法試験', 'display_name' => '司法試験', 'license_category_id' => 5, 'sort_index' => 4],
			37 => ['name' => '司法試験予備試験', 'display_name' => '司法試験予備試験', 'license_category_id' => 5, 'sort_index' => 5],
			38 => ['name' => '司法書士', 'display_name' => '司法書士', 'license_category_id' => 5, 'sort_index' => 6],
			39 => ['name' => '行政書士', 'display_name' => '行政書士', 'license_category_id' => 5, 'sort_index' => 7],
			40 => ['name' => '不動産鑑定士', 'display_name' => '不動産鑑定士', 'license_category_id' => 5, 'sort_index' => 8],
			41 => ['name' => '宅地建物取引士', 'display_name' => '宅建', 'license_category_id' => 5, 'sort_index' => 9],
			42 => ['name' => '土地家屋調査士', 'display_name' => '土地家屋調査士', 'license_category_id' => 5, 'sort_index' => 10],
			43 => ['name' => '一級建築士', 'display_name' => '一級建築士', 'license_category_id' => 5, 'sort_index' => 11],
			44 => ['name' => '二級建築士', 'display_name' => '二級建築士', 'license_category_id' => 5, 'sort_index' => 12],
			45 => ['name' => '木造建築士', 'display_name' => '木造建築士', 'license_category_id' => 5, 'sort_index' => 13],
			46 => ['name' => '医師国家試験', 'display_name' => '医師国家試験', 'license_category_id' => 5, 'sort_index' => 14],
			47 => ['name' => '歯科医師国家試験', 'display_name' => '歯科医師国家試験', 'license_category_id' => 5, 'sort_index' => 15],
			48 => ['name' => '歯科医師国家予備試験', 'display_name' => '歯科医師国家予備試験', 'license_category_id' => 5, 'sort_index' => 16],
			49 => ['name' => '獣医師国家試験', 'display_name' => '獣医師', 'license_category_id' => 5, 'sort_index' => 17],
			50 => ['name' => '獣医師国家予備試験', 'display_name' => '獣医師国家予備試験', 'license_category_id' => 5, 'sort_index' => 18],
			51 => ['name' => '理容師', 'display_name' => '理容師', 'license_category_id' => 5, 'sort_index' => 19],
			52 => ['name' => '管理理容師', 'display_name' => '管理理容師', 'license_category_id' => 5, 'sort_index' => 20],
			53 => ['name' => '美容師', 'display_name' => '美容師', 'license_category_id' => 5, 'sort_index' => 21],
			54 => ['name' => '管理美容師', 'display_name' => '管理美容師', 'license_category_id' => 5, 'sort_index' => 22],
			55 => ['name' => 'クリーニング師', 'display_name' => 'クリーニング師', 'license_category_id' => 5, 'sort_index' => 23],
			56 => ['name' => '調理師', 'display_name' => '調理師', 'license_category_id' => 5, 'sort_index' => 24],
			57 => ['name' => '初生ひな鑑別師', 'display_name' => 'ひよこ鑑定士', 'license_category_id' => 5, 'sort_index' => 25],
			58 => ['name' => 'あん摩マッサージ指圧師', 'display_name' => 'あん摩マッサージ指圧師', 'license_category_id' => 5, 'sort_index' => 26],
			59 => ['name' => 'はり師', 'display_name' => 'はり師', 'license_category_id' => 5, 'sort_index' => 27],
			60 => ['name' => 'きゅう師', 'display_name' => 'きゅう師', 'license_category_id' => 5, 'sort_index' => 28],
			61 => ['name' => '柔道整復師', 'display_name' => '柔道整復師', 'license_category_id' => 5, 'sort_index' => 29],
			62 => ['name' => '製菓衛生師', 'display_name' => '製菓衛生師', 'license_category_id' => 5, 'sort_index' => 30],
			63 => ['name' => '海事代理士', 'display_name' => '海事代理士', 'license_category_id' => 5, 'sort_index' => 31],
			64 => ['name' => 'パン製造技能士', 'display_name' => 'パン製造技能士', 'license_category_id' => 5, 'sort_index' => 32],
			65 => ['name' => 'システム監査技術者', 'display_name' => 'AU', 'license_category_id' => 6, 'sort_index' => 1],
			66 => ['name' => 'ＩＴストラテジスト', 'display_name' => 'ST', 'license_category_id' => 6, 'sort_index' => 2],
			67 => ['name' => 'プロジェクトマネージャ', 'display_name' => 'PM', 'license_category_id' => 6, 'sort_index' => 3],
			68 => ['name' => 'ネットワークスペシャリスト', 'display_name' => 'NW', 'license_category_id' => 6, 'sort_index' => 4],
			69 => ['name' => 'データベーススペシャリスト', 'display_name' => 'DB', 'license_category_id' => 6, 'sort_index' => 5],
			70 => ['name' => 'ＩＴサービスマネージャ', 'display_name' => 'SM', 'license_category_id' => 6, 'sort_index' => 6],
			71 => ['name' => 'エンベデッドシステムスペシャリスト', 'display_name' => 'ES', 'license_category_id' => 6, 'sort_index' => 7],
			72 => ['name' => '情報処理安全確保支援士', 'display_name' => 'SC', 'license_category_id' => 6, 'sort_index' => 8],
			73 => ['name' => 'システムアーキテクト', 'display_name' => 'SA', 'license_category_id' => 6, 'sort_index' => 9],
			74 => ['name' => '応用情報技術者試験', 'display_name' => 'AP', 'license_category_id' => 6, 'sort_index' => 10],
			75 => ['name' => '情報セキュリティマネジメント', 'display_name' => 'SG', 'license_category_id' => 6, 'sort_index' => 11],
			76 => ['name' => 'ITパスポート試験', 'display_name' => 'IP', 'license_category_id' => 6, 'sort_index' => 12],
			77 => ['name' => '（新）基本情報技術者試験', 'display_name' => 'FE', 'license_category_id' => 6, 'sort_index' => 13],
			78 => ['name' => 'ウェブデザイン技能検定', 'display_name' => 'ウェブデザイン技能検定', 'license_category_id' => 6, 'sort_index' => 14],
			79 => ['name' => '金融窓口サービス技能士', 'display_name' => '金融窓口サービス技能士　1級', 'license_category_id' => 7, 'sort_index' => 1],
			80 => ['name' => '知的財産管理技能検定', 'display_name' => '知的財産管理技能検定　1級', 'license_category_id' => 7, 'sort_index' => 2],
			81 => ['name' => '指定自動車教習所指導員', 'display_name' => '指定自動車教習所指導員', 'license_category_id' => 8, 'sort_index' => 1],
			82 => ['name' => '航空士', 'display_name' => '一等航空士', 'license_category_id' => 8, 'sort_index' => 2],
			83 => ['name' => '航空整備士', 'display_name' => '一等航空整備士', 'license_category_id' => 8, 'sort_index' => 3],
			84 => ['name' => '航空機関士', 'display_name' => '航空機関士', 'license_category_id' => 8, 'sort_index' => 4],
			85 => ['name' => '航空通信士', 'display_name' => '航空通信士', 'license_category_id' => 8, 'sort_index' => 5],
			86 => ['name' => '定期運送用操縦士', 'display_name' => '定期運送用操縦士', 'license_category_id' => 8, 'sort_index' => 6],
			87 => ['name' => '事業用操縦士', 'display_name' => '事業用操縦士（飛行機､飛行船）', 'license_category_id' => 8, 'sort_index' => 7],
			88 => ['name' => '自家用操縦士', 'display_name' => '自家用操縦士（滑空機）', 'license_category_id' => 8, 'sort_index' => 8],
			89 => ['name' => '航空工場整備士', 'display_name' => '航空工場整備士', 'license_category_id' => 8, 'sort_index' => 9],
			90 => ['name' => '運航管理者', 'display_name' => '運航管理者', 'license_category_id' => 8, 'sort_index' => 10],
			91 => ['name' => '航空運行整備士', 'display_name' => '一等航空運行整備士', 'license_category_id' => 8, 'sort_index' => 11],
			92 => ['name' => '航空管制官', 'display_name' => '航空管制官', 'license_category_id' => 8, 'sort_index' => 12],
			93 => ['name' => '航空工場検査員', 'display_name' => '航空工場検査員', 'license_category_id' => 8, 'sort_index' => 13],
			94 => ['name' => '海技士', 'display_name' => '海技士　1級　（航海）', 'license_category_id' => 8, 'sort_index' => 14],
			95 => ['name' => '機関当直三級海技士', 'display_name' => '機関当直三級海技士　（機関）', 'license_category_id' => 8, 'sort_index' => 15],
			96 => ['name' => '船橋当直3級海技士', 'display_name' => '船橋当直3級海技士　（航海）', 'license_category_id' => 8, 'sort_index' => 16],
			97 => ['name' => '救命艇手', 'display_name' => '救命艇手', 'license_category_id' => 8, 'sort_index' => 17],
			98 => ['name' => '船舶に乗り組む衛生管理者', 'display_name' => '船舶に乗り組む衛生管理者', 'license_category_id' => 8, 'sort_index' => 18],
			99 => ['name' => '船舶料理士', 'display_name' => '船舶料理士', 'license_category_id' => 8, 'sort_index' => 19],
			100 => ['name' => '水先人', 'display_name' => '一級水先人', 'license_category_id' => 8, 'sort_index' => 20],
			101 => ['name' => '船内荷役作業主任者', 'display_name' => '船内荷役作業主任者', 'license_category_id' => 8, 'sort_index' => 21],
			102 => ['name' => '揚貨装置運転士', 'display_name' => '揚貨装置運転士', 'license_category_id' => 8, 'sort_index' => 22],
			103 => ['name' => '国家公務員試験', 'display_name' => '国家公務員試験', 'license_category_id' => 9, 'sort_index' => 1],
			104 => ['name' => '国会議員政策担当秘書', 'display_name' => '国会議員政策担当秘書', 'license_category_id' => 9, 'sort_index' => 2],
			105 => ['name' => '国立国会図書館職員', 'display_name' => '国立国会図書館職員', 'license_category_id' => 9, 'sort_index' => 3],
			106 => ['name' => '文化庁発掘調査研究職員', 'display_name' => '文化庁発掘調査研究職員', 'license_category_id' => 9, 'sort_index' => 4],
			107 => ['name' => '社会教育主事・社会教育主事補', 'display_name' => '社会教育主事・社会教育主事補', 'license_category_id' => 9, 'sort_index' => 5],
			108 => ['name' => '労働基準監督官', 'display_name' => '労働基準監督官', 'license_category_id' => 9, 'sort_index' => 6],
			109 => ['name' => '国税専門官', 'display_name' => '国税専門官', 'license_category_id' => 9, 'sort_index' => 7],
			110 => ['name' => '法務教官', 'display_name' => '法務教官', 'license_category_id' => 9, 'sort_index' => 8],
			111 => ['name' => '刑務官', 'display_name' => '刑務官', 'license_category_id' => 9, 'sort_index' => 9],
			112 => ['name' => '衆議院事務局職員', 'display_name' => '衆議院事務局職員', 'license_category_id' => 9, 'sort_index' => 10],
			113 => ['name' => '参議院事務局職員', 'display_name' => '参議院事務局職員', 'license_category_id' => 9, 'sort_index' => 11],
			114 => ['name' => '裁判所事務官', 'display_name' => '裁判所事務官', 'license_category_id' => 9, 'sort_index' => 12],
			115 => ['name' => '家庭裁判所調査官補', 'display_name' => '家庭裁判所調査官補', 'license_category_id' => 9, 'sort_index' => 13],
			116 => ['name' => '防衛省職員', 'display_name' => '防衛省職員', 'license_category_id' => 9, 'sort_index' => 14],
			117 => ['name' => '自衛官候補生', 'display_name' => '自衛官候補生', 'license_category_id' => 9, 'sort_index' => 15],
			118 => ['name' => '自衛隊一般曹候補生', 'display_name' => '自衛隊一般曹候補生', 'license_category_id' => 9, 'sort_index' => 16],
			119 => ['name' => '警察官', 'display_name' => '警察官', 'license_category_id' => 9, 'sort_index' => 17],
			120 => ['name' => '気象大学校学生', 'display_name' => '気象大学校学生', 'license_category_id' => 9, 'sort_index' => 18],
			121 => ['name' => '入国警備官', 'display_name' => '入国警備官', 'license_category_id' => 9, 'sort_index' => 19],
			122 => ['name' => '皇宮護衛官', 'display_name' => '皇宮護衛官', 'license_category_id' => 9, 'sort_index' => 20],
			123 => ['name' => '小学校教諭免許状', 'display_name' => '小学校教諭免許状', 'license_category_id' => 9, 'sort_index' => 21],
			124 => ['name' => '中学校教諭免許状', 'display_name' => '中学校教諭免許状', 'license_category_id' => 9, 'sort_index' => 22],
			125 => ['name' => '高等学校諭免許状', 'display_name' => '高等学校諭免許状', 'license_category_id' => 9, 'sort_index' => 23],
			126 => ['name' => '特別支援学校教諭免許状', 'display_name' => '特別支援学校教諭免許状', 'license_category_id' => 9, 'sort_index' => 24],
			127 => ['name' => '学校図書館司書教諭', 'display_name' => '学校図書館司書教諭', 'license_category_id' => 9, 'sort_index' => 25],
			128 => ['name' => '幼稚園教諭免許状', 'display_name' => '幼稚園教諭免許状', 'license_category_id' => 9, 'sort_index' => 26],
			129 => ['name' => '保育士', 'display_name' => '保育士', 'license_category_id' => 9, 'sort_index' => 27],
			130 => ['name' => '防衛大学校学生', 'display_name' => '防衛大学校学生', 'license_category_id' => 9, 'sort_index' => 28],
			131 => ['name' => '防衛医科大学校学生', 'display_name' => '防衛医科大学校学生', 'license_category_id' => 9, 'sort_index' => 29],
			132 => ['name' => '自衛隊看護学生', 'display_name' => '自衛隊看護学生', 'license_category_id' => 9, 'sort_index' => 30],
			133 => ['name' => '海上・航空自衛隊航空学生', 'display_name' => '海上・航空自衛隊航空学生', 'license_category_id' => 9, 'sort_index' => 31],
			134 => ['name' => '自衛隊幹部候補生', 'display_name' => '自衛隊幹部候補生', 'license_category_id' => 9, 'sort_index' => 32],
			135 => ['name' => '海上保安学校学生', 'display_name' => '海上保安学校学生', 'license_category_id' => 9, 'sort_index' => 33],
			136 => ['name' => '航空保安大学校学生', 'display_name' => '航空保安大学校学生', 'license_category_id' => 9, 'sort_index' => 34],
			137 => ['name' => '消防官', 'display_name' => '消防官', 'license_category_id' => 9, 'sort_index' => 35],
			138 => ['name' => '財務専門官', 'display_name' => '財務専門官', 'license_category_id' => 9, 'sort_index' => 36],
			139 => ['name' => '税務職員採用試験', 'display_name' => '税務職員採用試験', 'license_category_id' => 9, 'sort_index' => 37],
			140 => ['name' => '食品衛生監視員', 'display_name' => '食品衛生監視員', 'license_category_id' => 9, 'sort_index' => 38],
			141 => ['name' => '精神保健福祉士', 'display_name' => '精神保健福祉士', 'license_category_id' => 10, 'sort_index' => 1],
			142 => ['name' => '社会福祉士', 'display_name' => '社会福祉士', 'license_category_id' => 10, 'sort_index' => 2],
			143 => ['name' => '介護福祉士', 'display_name' => '介護福祉士', 'license_category_id' => 10, 'sort_index' => 3],
			144 => ['name' => '栄養士', 'display_name' => '栄養士', 'license_category_id' => 11, 'sort_index' => 1],
			145 => ['name' => '管理栄養士', 'display_name' => '管理栄養士', 'license_category_id' => 11, 'sort_index' => 2],
			146 => ['name' => '薬剤師', 'display_name' => '薬剤師', 'license_category_id' => 11, 'sort_index' => 3],
			147 => ['name' => '看護師', 'display_name' => '看護師', 'license_category_id' => 11, 'sort_index' => 4],
			148 => ['name' => '保健師', 'display_name' => '保健師', 'license_category_id' => 11, 'sort_index' => 5],
			149 => ['name' => '助産師', 'display_name' => '助産師', 'license_category_id' => 11, 'sort_index' => 6],
			150 => ['name' => '救急救命士', 'display_name' => '救急救命士', 'license_category_id' => 11, 'sort_index' => 7],
			151 => ['name' => '診療放射線技師', 'display_name' => '診療放射線技師', 'license_category_id' => 11, 'sort_index' => 8],
			152 => ['name' => '臨床検査技師', 'display_name' => '臨床検査技師', 'license_category_id' => 11, 'sort_index' => 9],
			153 => ['name' => '臨床工学技士', 'display_name' => '臨床工学技士', 'license_category_id' => 11, 'sort_index' => 10],
			154 => ['name' => '歯科衛生士', 'display_name' => '歯科衛生士', 'license_category_id' => 11, 'sort_index' => 11],
			155 => ['name' => '歯科技工士', 'display_name' => '歯科技工士', 'license_category_id' => 11, 'sort_index' => 12],
			156 => ['name' => '理学療法士', 'display_name' => '理学療法士', 'license_category_id' => 11, 'sort_index' => 13],
			157 => ['name' => '義肢装具士', 'display_name' => '義肢装具士', 'license_category_id' => 11, 'sort_index' => 14],
			158 => ['name' => '言語聴覚士', 'display_name' => '言語聴覚士', 'license_category_id' => 11, 'sort_index' => 15],
			159 => ['name' => '作業療法士', 'display_name' => '作業療法士', 'license_category_id' => 11, 'sort_index' => 16],
			160 => ['name' => '視能訓練士', 'display_name' => '視能訓練士', 'license_category_id' => 11, 'sort_index' => 17],
			161 => ['name' => '登録販売者', 'display_name' => '登録販売者', 'license_category_id' => 11, 'sort_index' => 18],
			162 => ['name' => '公認心理師', 'display_name' => '公認心理師', 'license_category_id' => 11, 'sort_index' => 19],
			163 => ['name' => '中小企業診断士', 'display_name' => '中小企業診断士', 'license_category_id' => 12, 'sort_index' => 1],
			164 => ['name' => '社会保険労務士', 'display_name' => '社労士', 'license_category_id' => 12, 'sort_index' => 2],
			165 => ['name' => '土地区画整理士', 'display_name' => '土地区画整理士', 'license_category_id' => 12, 'sort_index' => 3],
			166 => ['name' => '労働安全コンサルタント', 'display_name' => '労働安全コンサルタント', 'license_category_id' => 12, 'sort_index' => 4],
			167 => ['name' => '労働衛生コンサルタント', 'display_name' => '労働衛生コンサルタント', 'license_category_id' => 12, 'sort_index' => 5],
			168 => ['name' => '旅行業務取扱管理者', 'display_name' => '旅行業務取扱管理者', 'license_category_id' => 12, 'sort_index' => 6],
			169 => ['name' => '職業訓練指導員', 'display_name' => '職業訓練指導員', 'license_category_id' => 12, 'sort_index' => 7],
			170 => ['name' => 'マンション管理士', 'display_name' => 'マンション管理士', 'license_category_id' => 12, 'sort_index' => 8],
			171 => ['name' => 'ファイナンシャル・プランニング技能士', 'display_name' => 'FP', 'license_category_id' => 12, 'sort_index' => 9],
			172 => ['name' => 'レストランサービス技能士', 'display_name' => 'レストランサービス技能士', 'license_category_id' => 12, 'sort_index' => 10],
			173 => ['name' => '管理業務主任者', 'display_name' => '管理業務主任者', 'license_category_id' => 12, 'sort_index' => 11],
			174 => ['name' => '土地改良換地士', 'display_name' => '土地改良換地士', 'license_category_id' => 12, 'sort_index' => 12],
			175 => ['name' => 'キャリアコンサルティング技能検定', 'display_name' => 'キャリアコンサルタント', 'license_category_id' => 12, 'sort_index' => 13],
			176 => ['name' => '警備員指導教育責任者', 'display_name' => '警備員指導教育責任者', 'license_category_id' => 12, 'sort_index' => 14],
			177 => ['name' => '貸金業務取扱主任者', 'display_name' => '貸金業務取扱主任者', 'license_category_id' => 12, 'sort_index' => 15],
			178 => ['name' => 'ビル設備管理技能士', 'display_name' => 'ビル設備管理技能士', 'license_category_id' => 12, 'sort_index' => 16],
			179 => ['name' => '消費生活相談員資格試験', 'display_name' => '消費生活相談員資格試験', 'license_category_id' => 12, 'sort_index' => 17],
			180 => ['name' => 'キャリアコンサルタント試験', 'display_name' => 'キャリアコンサルタント試験', 'license_category_id' => 12, 'sort_index' => 18],
			181 => ['name' => '計量士', 'display_name' => '計量士', 'license_category_id' => 13, 'sort_index' => 1],
			182 => ['name' => '公害防止管理者', 'display_name' => '公害防止管理者', 'license_category_id' => 13, 'sort_index' => 2],
			183 => ['name' => '建築物環境衛生管理技術者', 'display_name' => '建築物環境衛生管理技術者', 'license_category_id' => 13, 'sort_index' => 3],
			184 => ['name' => '廃棄物処理施設技術管理者', 'display_name' => '廃棄物処理施設技術管理者', 'license_category_id' => 13, 'sort_index' => 4],
			185 => ['name' => '浄化槽技術管理者', 'display_name' => '浄化槽技術管理者', 'license_category_id' => 13, 'sort_index' => 5],
			186 => ['name' => '浄化槽設備士', 'display_name' => '浄化槽設備士', 'license_category_id' => 13, 'sort_index' => 6],
			187 => ['name' => '浄化槽管理士', 'display_name' => '浄化槽管理士', 'license_category_id' => 13, 'sort_index' => 7],
			188 => ['name' => '浄化槽検査員', 'display_name' => '浄化槽検査員', 'license_category_id' => 13, 'sort_index' => 8],
			189 => ['name' => '浄化槽清掃技術者', 'display_name' => '浄化槽清掃技術者', 'license_category_id' => 13, 'sort_index' => 9],
			190 => ['name' => '臭気判定士', 'display_name' => '臭気判定士', 'license_category_id' => 13, 'sort_index' => 10],
			191 => ['name' => '有害液体汚染防止管理者', 'display_name' => '有害液体汚染防止管理者', 'license_category_id' => 13, 'sort_index' => 11],
			192 => ['name' => '放射線取扱主任者', 'display_name' => '放射線取扱主任者', 'license_category_id' => 13, 'sort_index' => 12],
			193 => ['name' => '核燃料取扱主任者', 'display_name' => '核燃料取扱主任者', 'license_category_id' => 13, 'sort_index' => 13],
			194 => ['name' => '原子炉主任技術者', 'display_name' => '原子炉主任技術者', 'license_category_id' => 13, 'sort_index' => 14],
			195 => ['name' => '造園施工管理技士', 'display_name' => '造園施工管理技士', 'license_category_id' => 13, 'sort_index' => 15],
			196 => ['name' => '特定化学物質及四ｱﾙｷﾙ鉛等作業主任者', 'display_name' => '特定化学物質及四ｱﾙｷﾙ鉛等作業主任者', 'license_category_id' => 13, 'sort_index' => 16],
			197 => ['name' => '油濁防止管理者', 'display_name' => '油濁防止管理者', 'license_category_id' => 13, 'sort_index' => 17],
			198 => ['name' => '特別管理産業廃棄物管理責任者', 'display_name' => '特別管理産業廃棄物管理責任者', 'license_category_id' => 13, 'sort_index' => 18],
			199 => ['name' => '空気環境測定実施者', 'display_name' => '空気環境測定実施者', 'license_category_id' => 13, 'sort_index' => 19],
			200 => ['name' => '土壌汚染調査技術管理者', 'display_name' => '土壌汚染調査技術管理者', 'license_category_id' => 13, 'sort_index' => 20],
			201 => ['name' => '外務省専門職員', 'display_name' => '外務省専門職員', 'license_category_id' => 14, 'sort_index' => 1],
			202 => ['name' => '通関士', 'display_name' => '通関士', 'license_category_id' => 14, 'sort_index' => 2],
			203 => ['name' => '全国通訳案内士', 'display_name' => '全国通訳案内士', 'license_category_id' => 14, 'sort_index' => 3],
			204 => ['name' => '測量士', 'display_name' => '測量士', 'license_category_id' => 15, 'sort_index' => 1],
			205 => ['name' => '発破技士', 'display_name' => '発破技士', 'license_category_id' => 15, 'sort_index' => 2],
			206 => ['name' => '土木施工管理技士', 'display_name' => '土木施工管理技士', 'license_category_id' => 15, 'sort_index' => 3],
			207 => ['name' => '建築施工管理技士', 'display_name' => '建築施工管理技士', 'license_category_id' => 15, 'sort_index' => 4],
			208 => ['name' => '建設機械施工技士', 'display_name' => '建設機械施工技士', 'license_category_id' => 15, 'sort_index' => 5],
			209 => ['name' => '車両系建設機械運転技能者', 'display_name' => '車両系建設機械運転技能者', 'license_category_id' => 15, 'sort_index' => 6],
			210 => ['name' => 'ショベルローダー等運転技能者', 'display_name' => 'ショベルローダー等運転技能者', 'license_category_id' => 15, 'sort_index' => 7],
			211 => ['name' => '管工事施工管理技士', 'display_name' => '管工事施工管理技士', 'license_category_id' => 15, 'sort_index' => 8],
			212 => ['name' => '建築設備士', 'display_name' => '建築設備士', 'license_category_id' => 15, 'sort_index' => 9],
			213 => ['name' => '建築設備検査員', 'display_name' => '建築設備検査員', 'license_category_id' => 15, 'sort_index' => 10],
			214 => ['name' => '特定建築物調査員資格者', 'display_name' => '特定建築物調査員資格者', 'license_category_id' => 15, 'sort_index' => 11],
			215 => ['name' => '昇降機等検査員', 'display_name' => '昇降機等検査員', 'license_category_id' => 15, 'sort_index' => 12],
			216 => ['name' => '消防設備士', 'display_name' => '消防設備士', 'license_category_id' => 15, 'sort_index' => 13],
			217 => ['name' => '消防設備点検資格者', 'display_name' => '消防設備点検資格者', 'license_category_id' => 15, 'sort_index' => 14],
			218 => ['name' => '衛生管理者', 'display_name' => '衛生管理者', 'license_category_id' => 15, 'sort_index' => 15],
			219 => ['name' => '衛生工学衛生管理者', 'display_name' => '衛生工学衛生管理者', 'license_category_id' => 15, 'sort_index' => 16],
			220 => ['name' => '作業環境測定士', 'display_name' => '作業環境測定士', 'license_category_id' => 15, 'sort_index' => 17],
			221 => ['name' => '林業架線作業主任者', 'display_name' => '林業架線作業主任者', 'license_category_id' => 15, 'sort_index' => 18],
			222 => ['name' => '砂利採取業務主任者', 'display_name' => '砂利採取業務主任者', 'license_category_id' => 15, 'sort_index' => 19],
			223 => ['name' => '採石業務管理者', 'display_name' => '採石業務管理者', 'license_category_id' => 15, 'sort_index' => 20],
			224 => ['name' => '採石のための掘削作業主任者', 'display_name' => '採石のための掘削作業主任者', 'license_category_id' => 15, 'sort_index' => 21],
			225 => ['name' => '地山の掘削及び土止め支保工作業主任者', 'display_name' => '地山の掘削及び土止め支保工作業主任者', 'license_category_id' => 15, 'sort_index' => 22],
			226 => ['name' => '酸素欠乏・硫化水素危険作業主任者', 'display_name' => '酸素欠乏・硫化水素危険作業主任者', 'license_category_id' => 15, 'sort_index' => 23],
			227 => ['name' => 'コンクリート造の工作物解体等作業主任者', 'display_name' => 'コンクリート造の工作物解体等作業主任者', 'license_category_id' => 15, 'sort_index' => 24],
			228 => ['name' => 'コンクリート破砕器作業主任者', 'display_name' => 'コンクリート破砕器作業主任者', 'license_category_id' => 15, 'sort_index' => 25],
			229 => ['name' => '型枠支保工の組立て等作業主任者', 'display_name' => '型枠支保工の組立て等作業主任者', 'license_category_id' => 15, 'sort_index' => 26],
			230 => ['name' => '足場の組立て等作業主任者', 'display_name' => '足場の組立て等作業主任者', 'license_category_id' => 15, 'sort_index' => 27],
			231 => ['name' => '建築物等の鉄骨の組立て等作業主任者', 'display_name' => '建築物等の鉄骨の組立て等作業主任者', 'license_category_id' => 15, 'sort_index' => 28],
			232 => ['name' => '木造建築物の組立て等作業主任者', 'display_name' => '木造建築物の組立て等作業主任者', 'license_category_id' => 15, 'sort_index' => 29],
			233 => ['name' => 'ガス溶接作業主任者', 'display_name' => 'ガス溶接作業主任者', 'license_category_id' => 15, 'sort_index' => 30],
			234 => ['name' => '危険物取扱者　その他', 'display_name' => '危険物取扱者　その他', 'license_category_id' => 15, 'sort_index' => 31],
			235 => ['name' => '第1種圧力容器取扱作業主任者', 'display_name' => '第1種圧力容器取扱作業主任者', 'license_category_id' => 15, 'sort_index' => 32],
			236 => ['name' => 'ボイラー技士', 'display_name' => 'ボイラー技士', 'license_category_id' => 15, 'sort_index' => 33],
			237 => ['name' => 'ボイラー整備士', 'display_name' => 'ボイラー整備士', 'license_category_id' => 15, 'sort_index' => 34],
			238 => ['name' => 'ボイラー溶接士', 'display_name' => 'ボイラー溶接士', 'license_category_id' => 15, 'sort_index' => 35],
			239 => ['name' => '小規模ボイラー取扱者', 'display_name' => '小規模ボイラー取扱者', 'license_category_id' => 15, 'sort_index' => 36],
			240 => ['name' => 'ガス主任技術者', 'display_name' => 'ガス主任技術者', 'license_category_id' => 15, 'sort_index' => 37],
			241 => ['name' => '高圧ガス製造保安責任者', 'display_name' => '高圧ガス製造保安責任者', 'license_category_id' => 15, 'sort_index' => 38],
			242 => ['name' => '高圧ガス販売主任者', 'display_name' => '高圧ガス販売主任者', 'license_category_id' => 15, 'sort_index' => 39],
			243 => ['name' => '高圧ガス移動監視者', 'display_name' => '高圧ガス移動監視者', 'license_category_id' => 15, 'sort_index' => 40],
			244 => ['name' => '特定高圧ガス取扱主任者', 'display_name' => '特定高圧ガス取扱主任者', 'license_category_id' => 15, 'sort_index' => 41],
			245 => ['name' => '液化石油ガス設備士', 'display_name' => '液化石油ガス設備士', 'license_category_id' => 15, 'sort_index' => 42],
			246 => ['name' => '高圧室内作業主任者', 'display_name' => '高圧室内作業主任者', 'license_category_id' => 15, 'sort_index' => 43],
			247 => ['name' => '酸素欠乏危険作業主任者', 'display_name' => '酸素欠乏危険作業主任者', 'license_category_id' => 15, 'sort_index' => 44],
			248 => ['name' => 'エックス線作業主任者', 'display_name' => 'エックス線作業主任者', 'license_category_id' => 15, 'sort_index' => 45],
			249 => ['name' => 'ガンマ線透過写真撮影作業主任者', 'display_name' => 'ガンマ線透過写真撮影作業主任者', 'license_category_id' => 15, 'sort_index' => 46],
			250 => ['name' => '火薬類取扱保安責任者', 'display_name' => '火薬類取扱保安責任者', 'license_category_id' => 15, 'sort_index' => 47],
			251 => ['name' => '火薬類製造保安責任者', 'display_name' => '火薬類製造保安責任者', 'license_category_id' => 15, 'sort_index' => 48],
			252 => ['name' => '有機溶剤作業主任者', 'display_name' => '有機溶剤作業主任者', 'license_category_id' => 15, 'sort_index' => 49],
			253 => ['name' => '給水装置工事主任技術者', 'display_name' => '給水装置工事主任技術者', 'license_category_id' => 15, 'sort_index' => 50],
			254 => ['name' => '石綿作業主任者', 'display_name' => '石綿作業主任者', 'license_category_id' => 15, 'sort_index' => 51],
			255 => ['name' => '鉛作業主任者', 'display_name' => '鉛作業主任者', 'license_category_id' => 15, 'sort_index' => 52],
			256 => ['name' => '高所作業車運転技能講習', 'display_name' => '高所作業車運転技能講習', 'license_category_id' => 15, 'sort_index' => 53],
			257 => ['name' => '木材加工用機械作業主任者', 'display_name' => '木材加工用機械作業主任者', 'license_category_id' => 15, 'sort_index' => 54],
			258 => ['name' => '乾燥設備作業主任者', 'display_name' => '乾燥設備作業主任者', 'license_category_id' => 15, 'sort_index' => 55],
			259 => ['name' => 'ダム管理主任技術者', 'display_name' => 'ダム管理主任技術者', 'license_category_id' => 15, 'sort_index' => 56],
			260 => ['name' => 'ダム水路主任技術者', 'display_name' => 'ダム水路主任技術者', 'license_category_id' => 15, 'sort_index' => 57],
			261 => ['name' => 'ずい道等の掘削等作業主任者', 'display_name' => 'ずい道等の掘削等作業主任者', 'license_category_id' => 15, 'sort_index' => 58],
			262 => ['name' => 'ずい道等の覆工作業主任者', 'display_name' => 'ずい道等の覆工作業主任者', 'license_category_id' => 15, 'sort_index' => 59],
			263 => ['name' => 'プレス機械作業主任者', 'display_name' => 'プレス機械作業主任者', 'license_category_id' => 15, 'sort_index' => 60],
			264 => ['name' => 'はい作業主任者', 'display_name' => 'はい作業主任者', 'license_category_id' => 15, 'sort_index' => 61],
			265 => ['name' => '警備業務検定', 'display_name' => '警備業務検定', 'license_category_id' => 15, 'sort_index' => 62],
			266 => ['name' => 'ガス溶接技能者', 'display_name' => 'ガス溶接技能者', 'license_category_id' => 15, 'sort_index' => 63],
			267 => ['name' => 'ガス消費機器設置工事監督者', 'display_name' => 'ガス消費機器設置工事監督者', 'license_category_id' => 15, 'sort_index' => 64],
			268 => ['name' => '鋼橋架設等作業主任者', 'display_name' => '鋼橋架設等作業主任者', 'license_category_id' => 15, 'sort_index' => 65],
			269 => ['name' => 'コンクリート橋架設等作業主任者', 'display_name' => 'コンクリート橋架設等作業主任者', 'license_category_id' => 15, 'sort_index' => 66],
			270 => ['name' => '毒物劇物取扱責任者', 'display_name' => '毒物劇物取扱責任者', 'license_category_id' => 15, 'sort_index' => 67],
			271 => ['name' => 'ボイラー・タービン主任技術者', 'display_name' => 'ボイラー・タービン主任技術者', 'license_category_id' => 15, 'sort_index' => 68],
			272 => ['name' => '機械警備業務管理者', 'display_name' => '機械警備業務管理者', 'license_category_id' => 15, 'sort_index' => 69],
			273 => ['name' => '貯水槽清掃作業監督者', 'display_name' => '貯水槽清掃作業監督者', 'license_category_id' => 15, 'sort_index' => 70],
			274 => ['name' => '清掃作業監督者', 'display_name' => '清掃作業監督者', 'license_category_id' => 15, 'sort_index' => 71],
			275 => ['name' => 'ダクト清掃作業監督者', 'display_name' => 'ダクト清掃作業監督者', 'license_category_id' => 15, 'sort_index' => 72],
			276 => ['name' => '排水管清掃作業監督者', 'display_name' => '排水管清掃作業監督者', 'license_category_id' => 15, 'sort_index' => 73],
			277 => ['name' => '防除作業監督者', 'display_name' => '防除作業監督者', 'license_category_id' => 15, 'sort_index' => 74],
			278 => ['name' => '統括管理者', 'display_name' => '統括管理者', 'license_category_id' => 15, 'sort_index' => 75],
			279 => ['name' => '空調給排水管理監督者', 'display_name' => '空調給排水管理監督者', 'license_category_id' => 15, 'sort_index' => 76],
			280 => ['name' => '防火対象物点検資格者', 'display_name' => '防火対象物点検資格者', 'license_category_id' => 15, 'sort_index' => 77],
			281 => ['name' => '防火管理者', 'display_name' => '防火管理者', 'license_category_id' => 15, 'sort_index' => 78],
			282 => ['name' => '防災管理点検資格者', 'display_name' => '防災管理点検資格者', 'license_category_id' => 15, 'sort_index' => 79],
			283 => ['name' => '防災管理者', 'display_name' => '防災管理者', 'license_category_id' => 15, 'sort_index' => 80],
			284 => ['name' => 'アーク溶接作業者', 'display_name' => 'アーク溶接作業者', 'license_category_id' => 15, 'sort_index' => 81],
			285 => ['name' => 'ジャッキ式つり上げ機械運転者', 'display_name' => 'ジャッキ式つり上げ機械運転者', 'license_category_id' => 15, 'sort_index' => 82],
			286 => ['name' => 'プレス金型取替作業者', 'display_name' => 'プレス金型取替作業者', 'license_category_id' => 15, 'sort_index' => 83],
			287 => ['name' => 'ボーリングマシン運転者', 'display_name' => 'ボーリングマシン運転者', 'license_category_id' => 15, 'sort_index' => 84],
			288 => ['name' => '刈払機取扱作業者', 'display_name' => '刈払機取扱作業者', 'license_category_id' => 15, 'sort_index' => 85],
			289 => ['name' => '巻上げ機（ウィンチ）運転者', 'display_name' => '巻上げ機（ウィンチ）運転者', 'license_category_id' => 15, 'sort_index' => 86],
			290 => ['name' => '家畜人工授精師', 'display_name' => '家畜人工授精師', 'license_category_id' => 15, 'sort_index' => 87],
			291 => ['name' => 'ピアノ調律技能士', 'display_name' => 'ピアノ調律技能士', 'license_category_id' => 15, 'sort_index' => 88],
			292 => ['name' => '解体工事施工技士', 'display_name' => '解体工事施工技士', 'license_category_id' => 15, 'sort_index' => 89],
			293 => ['name' => '不整地運搬車運転者', 'display_name' => '不整地運搬車運転者', 'license_category_id' => 15, 'sort_index' => 90],
			294 => ['name' => '安全衛生推進者', 'display_name' => '安全衛生推進者', 'license_category_id' => 15, 'sort_index' => 91],
			295 => ['name' => '警戒業務管理者・専従警戒要員', 'display_name' => '警戒業務管理者・専従警戒要員', 'license_category_id' => 15, 'sort_index' => 92],
			296 => ['name' => 'ゴンドラ操作者', 'display_name' => 'ゴンドラ操作者', 'license_category_id' => 15, 'sort_index' => 93],
			297 => ['name' => '防火設備検査員', 'display_name' => '防火設備検査員', 'license_category_id' => 15, 'sort_index' => 94],
			298 => ['name' => '建設用リフト運転士', 'display_name' => '建設用リフト運転士', 'license_category_id' => 15, 'sort_index' => 95],
			299 => ['name' => '機械保全技能士', 'display_name' => '機械保全技能士', 'license_category_id' => 15, 'sort_index' => 96],
			300 => ['name' => '病院清掃受託責任者', 'display_name' => '病院清掃受託責任者', 'license_category_id' => 15, 'sort_index' => 97],
			301 => ['name' => 'ビルクリーニング技能士', 'display_name' => 'ビルクリーニング技能士', 'license_category_id' => 15, 'sort_index' => 98],
			302 => ['name' => '潜水士', 'display_name' => '潜水士', 'license_category_id' => 15, 'sort_index' => 99],
			303 => ['name' => '技術士・技術士補', 'display_name' => '技術士・技術士補', 'license_category_id' => 16, 'sort_index' => 1],
			304 => ['name' => 'エネルギー管理士', 'display_name' => 'エネルギー管理士', 'license_category_id' => 16, 'sort_index' => 2],
			305 => ['name' => '電気工事施工管理技士', 'display_name' => '電気工事施工管理技士', 'license_category_id' => 16, 'sort_index' => 3],
			306 => ['name' => '電気工事士', 'display_name' => '電気工事士', 'license_category_id' => 16, 'sort_index' => 4],
			307 => ['name' => '電気通信主任技術者', 'display_name' => '電気通信主任技術者', 'license_category_id' => 16, 'sort_index' => 5],
			308 => ['name' => '電気主任技術者', 'display_name' => '電気主任技術者', 'license_category_id' => 16, 'sort_index' => 6],
			309 => ['name' => '工事担任者', 'display_name' => '工事担任者', 'license_category_id' => 16, 'sort_index' => 7],
			310 => ['name' => '飼料製造管理者', 'display_name' => '飼料製造管理者', 'license_category_id' => 16, 'sort_index' => 8],
			311 => ['name' => '電気取扱者', 'display_name' => '電気取扱者', 'license_category_id' => 16, 'sort_index' => 9],
			312 => ['name' => '電気通信工事施工管理技士', 'display_name' => '電気通信工事施工管理技士', 'license_category_id' => 16, 'sort_index' => 10],
			313 => ['name' => '情報配線施工技能士', 'display_name' => '情報配線施工技能士', 'license_category_id' => 16, 'sort_index' => 11],
			314 => ['name' => '総合無線通信士', 'display_name' => '総合無線通信士', 'license_category_id' => 17, 'sort_index' => 1],
			315 => ['name' => '海上無線通信士', 'display_name' => '海上無線通信士', 'license_category_id' => 17, 'sort_index' => 2],
			316 => ['name' => '陸上無線技術士', 'display_name' => '陸上無線技術士', 'license_category_id' => 17, 'sort_index' => 3],
			317 => ['name' => '航空無線通信士', 'display_name' => '航空無線通信士', 'license_category_id' => 17, 'sort_index' => 4],
			318 => ['name' => '海上特殊無線技士', 'display_name' => '海上特殊無線技士', 'license_category_id' => 17, 'sort_index' => 5],
			319 => ['name' => '陸上特殊無線技士', 'display_name' => '陸上特殊無線技士', 'license_category_id' => 17, 'sort_index' => 6],
			320 => ['name' => '航空特殊無線技士', 'display_name' => '航空特殊無線技士', 'license_category_id' => 17, 'sort_index' => 7],
			321 => ['name' => 'アマチュア無線技士', 'display_name' => 'アマチュア無線技士', 'license_category_id' => 17, 'sort_index' => 8],
			322 => ['name' => '小型船舶操縦士', 'display_name' => '小型船舶操縦士', 'license_category_id' => 18, 'sort_index' => 1],
			323 => ['name' => '高等学校卒業程度認定試験', 'display_name' => '高等学校卒業程度認定試験', 'license_category_id' => 18, 'sort_index' => 2],
			324 => ['name' => '和裁技能士', 'display_name' => '和裁技能士', 'license_category_id' => 18, 'sort_index' => 3],
			325 => ['name' => '気象予報士', 'display_name' => '気象予報士', 'license_category_id' => 18, 'sort_index' => 4],
			326 => ['name' => '司書・司書補', 'display_name' => '司書・司書補', 'license_category_id' => 18, 'sort_index' => 5],
			327 => ['name' => '学芸員・学芸員補', 'display_name' => '学芸員・学芸員補', 'license_category_id' => 18, 'sort_index' => 6],
			328 => ['name' => '食品衛生管理者', 'display_name' => '食品衛生管理者', 'license_category_id' => 18, 'sort_index' => 7],
			329 => ['name' => '狩猟免許', 'display_name' => '狩猟免許', 'license_category_id' => 18, 'sort_index' => 8],
			330 => ['name' => 'フリー入力', 'display_name' => 'フリー入力', 'license_category_id' => 999, 'sort_index' => 1],
		]);
	}

  private function confirmation($seeds) {
      print('以下の内容で登録更新します。' . PHP_EOL);

      foreach( $seeds as $key => $seed ) {
        $line = "[{$key}] ";

        foreach( $seed as $column => $value ) {
          $line .= "{$column}: {$value} ";
        }

        print($line . PHP_EOL);
      }

      print('本当に実行しますか？[y/n] ');
      $stdin = trim(fgets(STDIN));

      return preg_match('/^(y|Y).*$/', $stdin);
  }

}